# -*- coding: utf-8 -*-
"""
words_db.py
한국어 어학 학습 앱을 위한 단어 데이터베이스
"""

basic_words = [
    {"word": "사과", "meaning": "사과나무의 열매"},
    {"word": "바나나", "meaning": "열대 과일의 일종"},
    {"word": "고양이", "meaning": "포유류 동물, 집에서 기르는 애완동물"},
    {"word": "강아지", "meaning": "개의 새끼"},
    {"word": "학교", "meaning": "학생을 가르치는 교육 기관"},
    {"word": "친구", "meaning": "가까이 지내는 사람"},
    {"word": "선생님", "meaning": "학생을 가르치는 사람"},
    {"word": "책상", "meaning": "책을 읽거나 글을 쓸 때 사용하는 가구"},
    {"word": "컴퓨터", "meaning": "전자 계산 장치"},
    {"word": "전화기", "meaning": "멀리 있는 사람과 통화할 수 있는 기계"},
    {"word": "텔레비전", "meaning": "방송 프로그램을 보는 전자 기기"},
    {"word": "냉장고", "meaning": "음식을 차갑게 보관하는 가전제품"},
    {"word": "자동차", "meaning": "사람이나 짐을 싣고 다니는 교통수단"},
    {"word": "비행기", "meaning": "하늘을 나는 교통수단"},
    {"word": "기차", "meaning": "철로 위를 달리는 교통수단"},
    {"word": "병원", "meaning": "아픈 사람을 치료하는 곳"},
    {"word": "약국", "meaning": "약을 파는 가게"},
    {"word": "식당", "meaning": "음식을 만들어 파는 곳"},
    {"word": "시장", "meaning": "물건을 사고파는 곳"},
    {"word": "공원", "meaning": "사람들이 쉬거나 운동하는 공공 장소"},
    {"word": "도서관", "meaning": "책을 빌리거나 읽을 수 있는 곳"},
    {"word": "우체국", "meaning": "편지나 소포를 보내는 곳"},
    {"word": "은행", "meaning": "돈을 맡기거나 빌리는 곳"},
    {"word": "경찰서", "meaning": "경찰이 일하는 곳"},
    {"word": "소방서", "meaning": "소방관이 일하는 곳"},
    {"word": "가방", "meaning": "물건을 넣어 들고 다니는 용품"},
    {"word": "신발", "meaning": "발에 신는 물건"},
    {"word": "모자", "meaning": "머리에 쓰는 물건"},
    {"word": "안경", "meaning": "눈에 쓰는 물건"},
    {"word": "시계", "meaning": "시간을 알려주는 기계"},
    {"word": "연필", "meaning": "글씨를 쓰는 도구"},
    {"word": "지우개", "meaning": "연필로 쓴 글씨를 지우는 도구"},
    {"word": "공책", "meaning": "글을 쓰는 책"},
    {"word": "가위", "meaning": "종이나 천을 자르는 도구"},
    {"word": "풀", "meaning": "종이를 붙이는 도구"},
    {"word": "자", "meaning": "길이를 재는 도구"},
    {"word": "우산", "meaning": "비를 막는 도구"},
    {"word": "칫솔", "meaning": "이를 닦는 도구"},
    {"word": "치약", "meaning": "이를 닦을 때 사용하는 물질"},
    {"word": "비누", "meaning": "손이나 몸을 씻는 물질"},
    {"word": "수건", "meaning": "물기를 닦는 천"},
    {"word": "빗", "meaning": "머리를 빗는 도구"},
    {"word": "거울", "meaning": "자신의 모습을 비춰보는 물건"},
    {"word": "침대", "meaning": "잠을 자는 가구"},
    {"word": "이불", "meaning": "잠잘 때 덮는 물건"},
    {"word": "베개", "meaning": "머리를 괴는 물건"},
    {"word": "의자", "meaning": "앉는 가구"},
    {"word": "탁자", "meaning": "물건을 올려놓는 가구"},
    {"word": "창문", "meaning": "건물에서 밖을 보거나 환기하는 구조물"},
    {"word": "문", "meaning": "방이나 건물의 출입구"},
    {"word": "계단", "meaning": "높낮이가 다른 곳을 오르내리는 구조물"},
    {"word": "엘리베이터", "meaning": "사람이나 짐을 위아래로 옮기는 기계"},
    {"word": "에스컬레이터", "meaning": "움직이는 계단"},
    {"word": "봄", "meaning": "따뜻한 계절"},
    {"word": "여름", "meaning": "더운 계절"},
    {"word": "가을", "meaning": "선선한 계절"},
    {"word": "겨울", "meaning": "추운 계절"},
    {"word": "날씨", "meaning": "하늘의 상태"},
    {"word": "햇빛", "meaning": "태양의 빛"},
    {"word": "구름", "meaning": "하늘에 떠 있는 물방울이나 얼음 알갱이"},
    {"word": "비", "meaning": "하늘에서 내리는 물방울"},
    {"word": "눈", "meaning": "하늘에서 내리는 얼음 결정"},
    {"word": "바람", "meaning": "공기의 흐름"},
    {"word": "천둥", "meaning": "번개가 칠 때 나는 소리"},
    {"word": "번개", "meaning": "구름 사이에서 일어나는 전기 방전"},
    {"word": "무지개", "meaning": "비가 온 후 나타나는 일곱 빛깔의 띠"},
    {"word": "아침", "meaning": "해가 뜨는 때부터 낮까지의 시간"},
    {"word": "점심", "meaning": "낮에 먹는 식사"},
    {"word": "저녁", "meaning": "해가 질 무렵부터 밤까지의 시간"},
    {"word": "밤", "meaning": "해가 진 후부터 다음 날 해가 뜰 때까지"},
    {"word": "오늘", "meaning": "지금 지나가고 있는 이 날"},
    {"word": "어제", "meaning": "오늘의 바로 전날"},
    {"word": "내일", "meaning": "오늘의 바로 다음 날"},
    {"word": "월요일", "meaning": "한 주의 첫째 날"},
    {"word": "화요일", "meaning": "한 주의 둘째 날"},
    {"word": "수요일", "meaning": "한 주의 셋째 날"},
    {"word": "목요일", "meaning": "한 주의 넷째 날"},
    {"word": "금요일", "meaning": "한 주의 다섯째 날"},
    {"word": "토요일", "meaning": "한 주의 여섯째 날"},
    {"word": "일요일", "meaning": "한 주의 일곱째 날"},
    {"word": "가족", "meaning": "부부를 중심으로 한 친족 관계"},
    {"word": "아버지", "meaning": "자식을 낳아 기른 남자"},
    {"word": "어머니", "meaning": "자식을 낳아 기른 여자"},
    {"word": "형", "meaning": "남자가 남자 형제 중 손위를 부르는 말"},
    {"word": "누나", "meaning": "남자가 여자 형제 중 손위를 부르는 말"},
    {"word": "언니", "meaning": "여자가 여자 형제 중 손위를 부르는 말"},
    {"word": "오빠", "meaning": "여자가 남자 형제 중 손위를 부르는 말"},
    {"word": "동생", "meaning": "손아래 형제나 자매"},
    {"word": "할아버지", "meaning": "아버지의 아버지"},
    {"word": "할머니", "meaning": "아버지의 어머니"},
    {"word": "삼촌", "meaning": "아버지의 남자 형제"},
    {"word": "이모", "meaning": "어머니의 여자 형제"},
    {"word": "고모", "meaning": "아버지의 여자 형제"},
    {"word": "사촌", "meaning": "부모의 형제자매의 자녀"},
    {"word": "밥", "meaning": "쌀을 물과 함께 끓여 익힌 음식"},
    {"word": "국", "meaning": "국물이 있는 음식"},
    {"word": "김치", "meaning": "배추 등을 소금에 절여 양념에 버무린 음식"},
    {"word": "빵", "meaning": "밀가루를 발효시켜 구운 음식"},
    {"word": "우유", "meaning": "소의 젖"},
    {"word": "물", "meaning": "마시는 액체"},
    {"word": "차", "meaning": "차 잎을 우려낸 음료"},
    {"word": "커피", "meaning": "커피 콩을 볶아 끓인 음료"},
    {"word": "주스", "meaning": "과일이나 채소를 짜낸 음료"},
    {"word": "라면", "meaning": "밀가루를 반죽하여 만든 국수"},
    {"word": "떡", "meaning": "곡식 가루를 쪄서 만든 음식"},
    {"word": "과자", "meaning": "밀가루나 곡식 가루로 만든 간식"},
    {"word": "사탕", "meaning": "설탕으로 만든 단 음식"},
    {"word": "초콜릿", "meaning": "카카오로 만든 단 음식"},
    {"word": "아이스크림", "meaning": "우유와 설탕을 얼린 음식"},
    {"word": "피자", "meaning": "밀가루 반죽 위에 토마토소스와 치즈를 올려 구운 음식"},
    {"word": "치킨", "meaning": "닭고기를 튀긴 음식"},
    {"word": "햄버거", "meaning": "빵 사이에 고기와 채소를 넣은 음식"},
    {"word": "샐러드", "meaning": "채소를 섞어 만든 음식"},
    {"word": "국수", "meaning": "밀가루를 가늘게 만든 음식"},
    {"word": "만두", "meaning": "밀가루 반죽에 소를 넣어 만든 음식"},
    {"word": "김밥", "meaning": "밥과 재료를 김으로 싼 음식"},
    {"word": "계란", "meaning": "닭이 낳은 알"},
    {"word": "고기", "meaning": "동물의 살"},
    {"word": "생선", "meaning": "물고기"},
    {"word": "야채", "meaning": "채소"},
    {"word": "과일", "meaning": "나무나 풀에서 열리는 먹을 수 있는 열매"},
    {"word": "포도", "meaning": "둥글고 작은 열매가 송이로 달리는 과일"},
    {"word": "수박", "meaning": "크고 둥근 여름 과일"},
    {"word": "참외", "meaning": "노란색의 작은 여름 과일"},
    {"word": "딸기", "meaning": "빨간색의 작고 달콤한 과일"},
    {"word": "복숭아", "meaning": "털이 있는 둥근 과일"},
    {"word": "배", "meaning": "크고 둥근 가을 과일"},
    {"word": "감", "meaning": "주황색의 가을 과일"},
    {"word": "귤", "meaning": "작고 둥근 주황색 과일"},
    {"word": "오렌지", "meaning": "둥근 주황색 열대 과일"},
    {"word": "레몬", "meaning": "신맛이 나는 노란 과일"},
    {"word": "키위", "meaning": "갈색 털이 있는 녹색 과일"},
    {"word": "망고", "meaning": "노란색의 열대 과일"},
    {"word": "파인애플", "meaning": "가시가 있는 열대 과일"},
    {"word": "체리", "meaning": "작고 빨간 과일"},
    {"word": "토마토", "meaning": "빨간색의 채소 겸 과일"},
    {"word": "당근", "meaning": "주황색의 긴 채소"},
    {"word": "양파", "meaning": "둥근 매운 채소"},
    {"word": "감자", "meaning": "땅속에서 자라는 둥근 채소"},
    {"word": "고구마", "meaning": "땅속에서 자라는 달콤한 채소"},
    {"word": "배추", "meaning": "김치를 만드는 채소"},
    {"word": "무", "meaning": "흰색의 긴 채소"},
    {"word": "상추", "meaning": "쌈을 싸 먹는 채소"},
    {"word": "오이", "meaning": "초록색의 긴 채소"},
    {"word": "호박", "meaning": "크고 둥근 채소"},
    {"word": "가지", "meaning": "보라색의 긴 채소"},
    {"word": "파", "meaning": "길고 매운 향이 나는 채소"},
    {"word": "마늘", "meaning": "작고 매운 향이 나는 채소"},
    {"word": "고추", "meaning": "빨갛고 매운 채소"},
]
